version: '3.8'

services:
  # Redis 服务
  redis:
    image: redis:6.2
    container_name: warehouse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - warehouse-network

  # RabbitMQ 服务
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: warehouse-rabbitmq
    ports:
      - "5672:5672"   # AMQP 协议端口
      - "15672:15672" # 管理界面端口
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - warehouse-network

  # XXL-Job Admin 服务
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.3.1
    container_name: warehouse-xxl-job-admin
    ports:
      - "8080:8080"
    environment:
      PARAMS: >-
        --spring.datasource.url=jdbc:mysql://xxl-job-db:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        --spring.datasource.username=root
        --spring.datasource.password=root
        --xxl.job.accessToken=
    depends_on:
      - xxl-job-db
    restart: unless-stopped
    networks:
      - warehouse-network

  # XXL-Job 数据库
  xxl-job-db:
    image: mysql:5.7
    container_name: warehouse-xxl-job-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xxl_job
    volumes:
      - xxl-job-db-data:/var/lib/mysql
      - ./init-xxl-job-db.sql:/docker-entrypoint-initdb.d/init-xxl-job-db.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    networks:
      - warehouse-network

  # PostgreSQL 数据库 (用于主应用)
  postgres:
    image: postgres:13
    container_name: warehouse-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse_workflow
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - warehouse-network

volumes:
  redis-data:
  rabbitmq-data:
  xxl-job-db-data:
  postgres-data:

networks:
  warehouse-network:
    driver: bridge
